[versions]
minecraft = "1.21.10"
fabric-loader = "0.17.3"
fabric-api = "0.136.0+1.21.10"
fabric-loom = "1.12-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
