[versions]
minecraft = "1.21.9"
yarn = "1.21.9+build.1"
fabric-loader = "0.17.2"
fabric-api = "0.134.0+1.21.9"
fabric-loom = "1.11-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
