[versions]
minecraft = "1.21.6"
yarn = "1.21.6+build.1"
fabric-loader = "0.16.14"
fabric-api = "0.128.1+1.21.6"
fabric-loom = "1.10-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
