[versions]
curseforgegradle = "1.1.28"
minecraft = "1.21.11"
minotaur = "2.8.10"
fabric-loader = "0.18.1"
fabric-api = "0.139.4+1.21.11"
fabric-loom = "1.14-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "curseforgegradle" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
